FROM alpine:3.19 AS certs
RUN apk --no-cache add ca-certificates tzdata

FROM scratch

WORKDIR /app

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=certs /usr/share/zoneinfo /usr/share/zoneinfo

ARG TARGETARCH

COPY bin/backend-linux-${TARGETARCH} ./dockercrafter-backend
COPY config.yaml .

# Port exposed by the application
EXPOSE 12581

CMD ["./dockercrafter-backend"]
